[package]
name = "hayagriva"
version = "0.3.2"
authors = ["Martin Haug <mhaug@live.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Work with references: Literature database management, storage, and citation formatting"
repository = "https://github.com/typst/hayagriva"
readme = "README.md"
categories = ["template-engine", "value-formatting", "command-line-utilities"]
keywords = ["bibliography", "citation", "reference", "bibtex", "literature"]

[features]
default = ["biblatex"]
cli = ["clap", "strum"]

[dependencies]
biblatex = { version = "0.8", optional = true }
clap = { version = "3.1", optional = true, features = ["cargo"] }
# Needed for legacy styles
isolang = "2.1"
strum = { version = "0.24", features = ["derive"], optional = true }
thiserror = "1.0.48"
unic-langid = { version = "0.9.0", features = ["serde"] }
unicode-segmentation = "1.6.0"
url = { version =  "2.4", features = ["serde"] }
unscanny = "0.1.0"
paste = "1.0.14"
serde = { version = "1", features = ["derive"] }
indexmap = { version = "2.0.2", features = ["serde"] }
serde_yaml = "0.9.25"

[[bin]]
name = "hayagriva"
required-features = ["cli"]

[patch.crates-io]
biblatex = { git = "https://github.com/typst/biblatex" }
