[package]
name = "hayagriva"
version = "0.1.0"
authors = ["Martin Haug <mhaug@live.de>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.15", default-features = false }
lazy_static = "1.4.0"
linked-hash-map = "0.5.3"
paste = "1.0.0"
regex = "1.3.9"
strum = "0.19.2"
strum_macros = "0.19.2"
thiserror = "1.0.20"
unic-langid = "0.9.0"
unicode-segmentation = "1.6.0"
url = "2.1.1"
yaml-rust = "0.4.4"
