name: Continuous integration
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - 
        name: Check out CSL styles
        run: |
          cd ..
          git clone --depth 1 https://github.com/citation-style-language/styles
      - run: cargo build
      - run: cargo test
